name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias y ejecutar pruebas
        working-directory: backend
        run: |
          npm install
          npm test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v2

      - name: Construir imagen Docker
        run: docker build -t tuusuario/mi-app:latest .

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push tuusuario/mi-app:latest